/**
 * Unit tests for decoder.ts — circuit-breaker Frozen/Unfrozen events.
 *
 * Fixtures are hand-crafted XDR bytes encoded as base64, matching the exact
 * wire format the circuit-breaker contract emits:
 *
 *   Frozen    topics: [Symbol("Frozen")]    data: Void
 *   Unfrozen  topics: [Symbol("Unfrozen")]  data: Void
 *
 * Both events carry no address payload — the contract_id column identifies
 * which circuit-breaker instance changed state.
 *
 * A regression suite confirms the existing AllowAdd event still decodes
 * correctly after the new event types were added.
 */

import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { decodeEvent } from "./decoder.js";
import type { RawSorobanEvent } from "./rpc.js";

// ─── XDR fixture helpers ──────────────────────────────────────────────────────

function u32Bytes(n: number): Uint8Array {
  const b = new Uint8Array(4);
  new DataView(b.buffer).setUint32(0, n, false);
  return b;
}

function xdrString(s: string): Uint8Array {
  const enc = new TextEncoder().encode(s);
  const pad = (4 - (enc.length % 4)) % 4;
  const out = new Uint8Array(4 + enc.length + pad);
  new DataView(out.buffer).setUint32(0, enc.length, false);
  out.set(enc, 4);
  return out;
}

function concat(...parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((n, a) => n + a.length, 0);
  const out = new Uint8Array(total);
  let pos = 0;
  for (const p of parts) { out.set(p, pos); pos += p.length; }
  return out;
}

function toB64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

const SC_VOID   = 1;
const SC_SYMBOL = 15;

function scVoid(): Uint8Array   { return u32Bytes(SC_VOID); }
function scSymbol(s: string): Uint8Array {
  return concat(u32Bytes(SC_SYMBOL), xdrString(s));
}

// ─── Pre-computed XDR fixtures ────────────────────────────────────────────────
// Generated by encoding the symbols "Frozen" and "Unfrozen" using the same
// XDR layout the Soroban SDK emits for symbol_short!() topics.

const FROZEN_T0   = "AAAADwAAAAZGcm96ZW4AAA=="; // Symbol("Frozen")
const UNFROZEN_T0 = "AAAADwAAAAhVbmZyb3plbg=="; // Symbol("Unfrozen")
const VOID_DATA   = "AAAAAQ==";                  // ScVal::Void

// ─── Shared helper ────────────────────────────────────────────────────────────

function makeRaw(
  topic: string[],
  value: string,
  overrides: Partial<RawSorobanEvent> = {}
): RawSorobanEvent {
  return {
    type: "contract",
    ledger: 9000,
    ledgerClosedAt: "2025-09-01T00:00:00Z",
    contractId: "CBREAKER",
    id: "0000-0001",
    pagingToken: "0000-0001",
    inSuccessfulContractCall: true,
    topic,
    value,
    ...overrides,
  };
}

const EXPECTED_TIMESTAMP = Math.floor(
  new Date("2025-09-01T00:00:00Z").getTime() / 1000
);

// ─── circuit-breaker: Frozen ──────────────────────────────────────────────────

describe("decodeEvent — circuit-breaker Frozen", () => {
  it("decodes eventType as Frozen", () => {
    const raw = makeRaw([FROZEN_T0], VOID_DATA);
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null, "expected non-null decoded event");
    assert.equal(decoded.eventType, "Frozen");
  });

  it("records contractId, ledgerSequence and timestamp", () => {
    const raw = makeRaw([FROZEN_T0], VOID_DATA);
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.contractId, "CBREAKER");
    assert.equal(decoded.ledgerSequence, 9000);
    assert.equal(decoded.timestamp, EXPECTED_TIMESTAMP);
  });

  it("all address and payload fields are null", () => {
    const raw = makeRaw([FROZEN_T0], VOID_DATA);
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.address,      null);
    assert.equal(decoded.addressTo,    null);
    assert.equal(decoded.amount,       null);
    assert.equal(decoded.jurisdiction, null);
    assert.equal(decoded.policyFrom,   null);
    assert.equal(decoded.policyTo,     null);
    assert.equal(decoded.policyPassed, null);
  });

  it("stores rawTopics and rawData", () => {
    const raw = makeRaw([FROZEN_T0], VOID_DATA);
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.rawTopics, JSON.stringify([FROZEN_T0]));
    assert.equal(decoded.rawData,   VOID_DATA);
  });

  it("still decodes when value field is empty string", () => {
    // Soroban may omit the data field; decoder should handle gracefully
    const raw = makeRaw([FROZEN_T0], "");
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.eventType, "Frozen");
  });
});

// ─── circuit-breaker: Unfrozen ────────────────────────────────────────────────

describe("decodeEvent — circuit-breaker Unfrozen", () => {
  it("decodes eventType as Unfrozen", () => {
    const raw = makeRaw([UNFROZEN_T0], VOID_DATA);
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null, "expected non-null decoded event");
    assert.equal(decoded.eventType, "Unfrozen");
  });

  it("records contractId and ledgerSequence", () => {
    const raw = makeRaw([UNFROZEN_T0], VOID_DATA, {
      contractId: "CBREAKER2",
      ledger: 9001,
    });
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.contractId,     "CBREAKER2");
    assert.equal(decoded.ledgerSequence, 9001);
  });

  it("all address and payload fields are null", () => {
    const raw = makeRaw([UNFROZEN_T0], VOID_DATA);
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.address,      null);
    assert.equal(decoded.addressTo,    null);
    assert.equal(decoded.amount,       null);
    assert.equal(decoded.jurisdiction, null);
    assert.equal(decoded.policyFrom,   null);
    assert.equal(decoded.policyTo,     null);
    assert.equal(decoded.policyPassed, null);
  });
});

// ─── Guards ───────────────────────────────────────────────────────────────────

describe("decodeEvent — circuit-breaker guards", () => {
  it("returns null for an empty topic array", () => {
    const raw = makeRaw([], VOID_DATA);
    assert.equal(decodeEvent(raw), null);
  });

  it("returns null for an unknown symbol", () => {
    const unknownT0 = toB64(scSymbol("CircuitTrip"));
    const raw = makeRaw([unknownT0], VOID_DATA);
    assert.equal(decodeEvent(raw), null);
  });

  it("Frozen and Unfrozen are distinct event types", () => {
    const frozen   = decodeEvent(makeRaw([FROZEN_T0],   VOID_DATA));
    const unfrozen = decodeEvent(makeRaw([UNFROZEN_T0], VOID_DATA));
    assert.ok(frozen   !== null);
    assert.ok(unfrozen !== null);
    assert.notEqual(frozen.eventType, unfrozen.eventType);
  });
});

// ─── Regression: existing events still decode correctly ───────────────────────

describe("regression — existing AllowAdd event unaffected", () => {
  it("AllowAdd decodes after circuit-breaker events were added", () => {
    const SC_ADDRESS = 18, SC_ACCOUNT = 0;
    const t0 = toB64(scSymbol("AllowAdd"));
    const t1 = toB64(concat(
      u32Bytes(SC_ADDRESS), u32Bytes(SC_ACCOUNT), u32Bytes(0),
      new Uint8Array(32).fill(0xAA)
    ));
    const raw = makeRaw([t0, t1], toB64(scVoid()), { contractId: "CALLOWLIST" });
    const decoded = decodeEvent(raw);
    assert.ok(decoded !== null);
    assert.equal(decoded.eventType, "AllowAdd");
    assert.ok(decoded.address !== null);
    assert.equal(decoded.policyFrom,   null);
    assert.equal(decoded.policyPassed, null);
  });
});
